[project]
name = "parakeet-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cuda-python>=13.0.0",
    "nemo-toolkit[asr]>=2.4.0",
    "onnx-asr[cpu,hub]>=0.7.0",
    "onnxruntime>=1.22.1",
]
