[project]
name = "parakeet-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cuda-python>=13.0.0; sys_platform == 'linux'",
    "nemo-toolkit[asr]>=2.4.0; sys_platform == 'linux'",
    "pydub>=0.25.1",
]
